from enum import Enum

CMD_SYNC = 'S'
CMD_DISC = 'D'
CMD_DISC_REPLY = 'DR'
CMD_DATA_COLLECTION = 'C'
CMD_DATA_COLLECTION_REPLY = 'CR'

# Packet payload: DEV_ID # PACKET_SEQ_NR # CMD # DATA # NR_OF_RETRANSMISSIONS
PAYLOAD = Enum('Payload', 'ID SEQ CMD DATA NR_OF_RET RSSI')

# device/radio state
STATE_ON = 'ON'
STATE_OFF = 'OFF'
STATE_SLEEP = 'SLEEP'
STATE_SIM_END = 'END'
SUBSTATE_NONE = 'NONE'
SUBSTATE_SIM_END = 'END'

# device additional substate - while ON and not IDLE
D_SUBSTATE_OP = 'OP'

# radio additional substate
R_SUBSTATE_RX = 'RX'
R_SUBSTATE_TX = 'TX'

STATE = [STATE_ON, STATE_OFF, STATE_SLEEP]
D_SUBSTATE = [SUBSTATE_NONE, D_SUBSTATE_OP]
R_SUBSTATE = [SUBSTATE_NONE, R_SUBSTATE_RX, R_SUBSTATE_TX]